### ISSUE TITLE
Encoding problems for  _ / left-arrow and ^ uparrow in SAILDART.org

### ISSUE THREAD

**Issue by masinter** [white-flame/eurisko#1]
In the beginning Interlisp was made for PDP-10/Tenex systemss where the character code for left-arrow was what is now and and the character code for up-rrow was what is now ^.

(My undersanding is that these code assignments were inherited from an earlier version of ASCII.

Bruce Baumgart prducing SAILDART.org did a great job of translating 9-bit PRE-ASCII codes to something you can read in a browser and display with left-arrow and up-arrow rather than _ and ^. 
(Lenat's files on saildart](https://www.saildart.org[AM,DBL]/)

The differet interpretations are supported through (some of) the fonts you get. 
If you want a file you can LOAD or compile in modern Medley and have it work, you will likely need to partially undo this transformation.  

A sunoke character replacement using tr or otherwise would solve this problem.

_ isn't used ofteninInterlisp (except in Loops) -- ceating an instance of a datatype, for example.
I don't think ^ is used except for prefixing control-character text representation.

but the use of _ might explain reported problems with the code.

**Comment by white-flame** [comment]
Huh, yeah Commodore PETSCII used the same encoding for those 2 characters, so that's quite familiar to me.

The unicode "←" only appears in some of the "Snazzy" GUI routines. I skipped over those when reverse engineering what was going on, so I hadn't noticed them until now. I don't see any "↑" or "^" in that original EUR file, nor "_".

seveno4's edits to get it running in Medley seem to have rewritten those to a different API, and those no longer use the left-arrow in the source, but still display the GUI. I do think that people seeking to run it in Medley should start from his version, not the raw original. I'll make that more clear in the readme.

If people are having problems running the code from my repo (which is intended to be the unmodified artifact), I haven't seen it reported here, but if they're going straight from SAILDART, I could understand that.  I'll certainly make note of that character issue in the readme as well.

**Comment by white-flame** [comment]
Done. Thanks!
